name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          
      - name: Create docker image of the app
        run: docker load --input src/test/resources/todo-app.tar
        
      - name: Build with Gradle
        run: ./gradlew test
        
      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/tests
          
      - name: Run a one-line script
        run: echo ls -a
        
      - name: Publish reports
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tests
